# Behavior Node Configuration File
# 行为节点配置文件

behavior_node:
  # 系统基础配置
  system:
    vehicle_id: 1
    vehicle_type: 2  # 1:固定翼, 2:旋翼, 3:垂起, 4:小车
    main_tree_file: "main_behavior_tree.xml"
    tick_rate_hz: 10.0
    execution_timeout_ms: 1000
    blackboard_namespace: "behavior_node"

  # 飞行参数配置
  flight:
    takeoff_altitude: 50.0
    max_altitude: 500.0
    min_altitude: 5.0
    cruise_speed: 15.0
    max_speed: 25.0
    min_speed: 3.0
    arrival_distance: 10.0
    anti_collision_distance: 20.0
    emergency_land_battery: 15.0  # 紧急降落电量阈值
    critical_battery: 10.0        # 危险电量阈值

  # 导航参数
  navigation:
    default_speed: 12.0
    default_altitude: 100.0
    max_waypoint_distance: 10000.0  # 最大航点间距（米）
    min_waypoint_distance: 10.0     # 最小航点间距（米）
    default_loops: 1
    waypoint_tolerance: 5.0
    heading_tolerance: 10.0  # 度

  # 搜索参数
  search:
    default_pattern: "GRID"
    default_speed: 10.0
    default_altitude: 80.0
    coverage_width: 50.0
    search_timeout: 600.0  # 搜索超时（秒）
    target_confidence_threshold: 0.7
    target_max_age: 5.0    # 目标最大年龄（秒）

    # 目标类别定义
    target_classes:
      unknown: 0
      vehicle: 1
      person: 2
      building: 3
      aircraft: 4

  # 编队参数
  formation:
    max_members: 10
    min_members: 2
    default_spacing: 20.0
    max_spacing: 100.0
    min_spacing: 10.0
    assembly_timeout: 300.0
    assembly_radius: 50.0

    # 编队类型定义
    formation_types:
      line: 0
      wedge: 1
      diamond: 2
      column: 3
      echelon_left: 4
      echelon_right: 5

  # 攻击参数
  attack:
    max_range: 500.0
    min_range: 10.0
    tracking_timeout: 60.0
    attack_timeout: 30.0

    # 攻击模式
    attack_modes:
      manual: 0
      auto_track: 1
      coordinate: 2

  # 通信配置
  communication:
    heartbeat_rate_hz: 1.0
    command_timeout_ms: 5000
    status_publish_rate_hz: 2.0
    max_connection_lost_time: 10.0  # 最大通信丢失时间（秒）

  # ROS话题配置
  topics:
    # 输出话题
    offboard_control: "/inner/set/offboard_ctrl"
    command_response: "/outer/response"
    task_status: "/outer/status/task"
    image_distribute: "/inner/set/image_distribute"
    coordinate_point: "/inner/set/coordinate"
    vehicle_type: "/inner/set/vehicle_type"
    anti_collision_distance: "/inner/set/anti_collision_distance"
    navline: "/inner/set/navline"
    group_ids: "/inner/set/ids"
    group_speed: "/inner/set/spd"
    group_offset: "/inner/set/offset"
    group_loops: "/inner/set/line_loops"
    point_tag: "/inner/set/point_tag"
    object_filter: "/inner/set/obj_filter"
    trace_attack_object: "/inner/set/trace_attack_object"

    # 输入话题
    ground_station_command: "/outer/set/stage_info_json"
    vehicle_state: "/mavros/state"
    battery_state: "/mavros/battery"
    gps_status: "/mavros/gps/fix"
    position_local: "/mavros/local_position/pose"
    attitude: "/mavros/local_position/pose"
    detected_targets: "/target/detected_objects"
    navigation_status: "/navigation/status"
    search_status: "/search/status"

  # ROS服务配置
  services:
    # 飞行控制服务
    lock_control: "/mavros/cmd/arming"
    flight_mode_control: "/mavros/set_mode"
    takeoff_control: "/mavros/cmd/takeoff"
    land_control: "/mavros/cmd/land"
    navigation_control: "/navigation/command"
    trace_attack_control: "/trace_attack/control"
    formation_switch: "/formation/switch"

    # 获取信息服务
    neighbor_ids: "/inner/get/neighbor_ids"
    rtsp_url: "/inner/get/rtsp_url"
    waypoint_distance: "/inner/get/waypt_dis"
    vehicle_type_get: "/inner/get/type_vehicle"

  # 黑板参数配置
  blackboard:
    # 任务参数
    mission_phase: "init"  # init, takeoff, navigation, search, attack, return
    current_stage: 0

    # 飞行参数
    takeoff_altitude: 50.0
    navigation_speed: 12.0
    search_speed: 10.0
    return_speed: 15.0
    arrival_distance: 10.0
    navigation_loops: 1

    # 搜索参数
    search_mode: "pattern"  # pattern, line
    target_class: 1
    search_area: []
    search_formation_offsets: []

    # 编队参数
    formation_enabled: false
    formation_type: 0
    formation_members: []
    formation_leader: 0
    formation_offsets: []

    # 位置参数
    home_position:
      x: 0.0
      y: 0.0
      z: 0.0
    assembly_point:
      x: 0.0
      y: 0.0
      z: 50.0

    # 航线参数
    waypoints: []
    return_waypoints: []

    # 攻击参数
    attack_mode: "manual"
    attack_target_position:
      x: 0.0
      y: 0.0
      z: 0.0
    attack_type: 0

  # 验证配置
  validation:
    waypoints:
      min_waypoints: 1
      max_waypoints: 100
      min_altitude: 5.0
      max_altitude: 500.0
      max_coordinate_range: 50000.0
      min_waypoint_distance: 5.0
      max_waypoint_distance: 5000.0
      check_coordinate_bounds: true
      check_waypoint_spacing: true

    search_area:
      min_vertices: 3
      min_altitude: 10.0
      max_altitude: 300.0
      min_area: 100.0      # 平方米
      max_area: 1000000.0  # 平方米
      check_area_size: true
      check_self_intersection: true

    flight_parameters:
      min_speed: 1.0
      max_speed: 30.0
      min_altitude: 5.0
      max_altitude: 500.0
      min_arrival_distance: 1.0
      max_arrival_distance: 100.0
      min_loops: -1
      max_loops: 1000
      check_loops: true

    formation:
      min_members: 1
      max_members: 20
      min_spacing: 5.0
      max_spacing: 200.0
      valid_formation_types: [0, 1, 2, 3, 4, 5]

  # 监控配置
  monitoring:
    health_check_interval: 5.0  # 秒
    status_report_interval: 1.0  # 秒
    log_level: "INFO"           # DEBUG, INFO, WARN, ERROR
    enable_performance_monitoring: true
    max_execution_time_ms: 100  # 单次tick最大执行时间

  # 安全配置
  safety:
    enable_geofence: true
    geofence_radius: 5000.0     # 地理围栏半径（米）
    enable_altitude_limit: true
    max_allowed_altitude: 500.0
    min_allowed_altitude: 5.0
    enable_speed_limit: true
    max_allowed_speed: 25.0
    enable_battery_monitor: true
    low_battery_threshold: 20.0
    critical_battery_threshold: 10.0

  # 调试配置
  debug:
    enable_bt_logging: false
    bt_log_directory: "/tmp/bt_logs"
    enable_state_visualization: false
    log_blackboard_updates: false
    log_node_execution: false