# config/test_scenarios.yaml

# 基础功能测试场景
basic_tests:
  set_home:
    timeout: 5.0
    expected_result: "success"
    parameters:
      lat: 39.9042
      lon: 116.4074
      alt: 50.0

  takeoff:
    timeout: 15.0
    expected_result: "mission_completed"
    expected_stage: 1
    parameters:
      target_altitude: 30.0
      climb_rate: 2.0

  goto_destination:
    timeout: 20.0
    expected_result: "mission_completed"
    expected_stage: 2
    parameters:
      target_position: [100.0, 50.0, -25.0]
      speed: 8.0
      arrival_distance: 2.0

  auto_trace:
    timeout: 10.0
    expected_result: "target_locked"
    expected_stage: 3
    parameters:
      search_duration: 5.0

  land:
    timeout: 15.0
    expected_result: "mission_completed"
    expected_stage: 4
    parameters:
      landing_speed: 1.0

# 复杂场景测试
complex_scenarios:
  full_mission:
    description: "完整任务流程测试"
    timeout: 120.0
    stages:
      - name: "takeoff"
        duration: 15.0
        parameters:
          altitude: 50.0
      - name: "patrol"
        duration: 30.0
        parameters:
          waypoints:
            - [50.0, 0.0, -50.0]
            - [50.0, 50.0, -50.0]
            - [0.0, 50.0, -50.0]
            - [0.0, 0.0, -50.0]
      - name: "search_and_track"
        duration: 20.0
        parameters:
          search_area: [100.0, 100.0]
      - name: "return_and_land"
        duration: 20.0

  emergency_scenarios:
    description: "紧急情况处理测试"
    low_battery:
      timeout: 30.0
      trigger_condition: "battery_level < 20%"
      expected_behavior: "emergency_landing"

    communication_loss:
      timeout: 60.0
      trigger_condition: "no_heartbeat > 5s"
      expected_behavior: "rtl_mode"

    target_lost:
      timeout: 15.0
      trigger_condition: "target_confidence < 0.3"
      expected_behavior: "search_pattern"

# 性能测试场景
performance_tests:
  response_time:
    description: "控制响应时间测试"
    iterations: 100
    acceptable_delay: 0.1  # seconds

  trajectory_accuracy:
    description: "轨迹跟踪精度测试"
    waypoints:
      - [0.0, 0.0, -30.0]
      - [100.0, 0.0, -30.0]
      - [100.0, 100.0, -30.0]
      - [0.0, 100.0, -30.0]
    acceptable_error: 1.0  # meters

  multi_target_tracking:
    description: "多目标跟踪测试"
    target_count: 5
    tracking_duration: 60.0
    min_tracking_accuracy: 0.8

# 压力测试场景
stress_tests:
  high_frequency_commands:
    description: "高频命令测试"
    command_rate: 100.0  # Hz
    duration: 30.0  # seconds

  memory_usage:
    description: "内存使用测试"
    duration: 300.0  # seconds
    max_memory_mb: 512

  long_duration:
    description: "长时间运行测试"
    duration: 3600.0  # seconds
    health_check_interval: 60.0