struct CommandRequest
{
    octet srcid;
    octet dstid;
    octet grpid;
    unsigned short type;
    long param0;
    long param1;
    long param2;
    long param3;
    long param4;
    float fparam5;
    float fparam6;
    float fparam7;
    float fparam8;

};