struct ObjectReport{
    octet id;
    unsigned long objid;    //目标身份id
    unsigned short cls;	     //目标分类
    octet  subcls;  //目标子分类
    octet  score;   //估计目标score
    long x;         //估计目标locx
    long y;         //估计目标locy
    long z;         //估计目标locz
    long vx;        //估计目标速度vx
    long vy;        //估计目标速度vy
    long vz;        //估计目标速度vz
};